/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InventoryManager;

import assignmentdecsix.Config;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class SuppliedItemsFrame extends javax.swing.JFrame {

    private ArrayList<Supplier> supplierList = new ArrayList<>();
    private ArrayList <SuppliedItems> suppliedItemsList = new ArrayList<>();
    private static FileManager<Supplier> supplierManager = new FileManager<>(Config.getSupplierPath());
    private static FileManager<SuppliedItems> suppliedItemsManager = new FileManager<>(Config.getSuppliedItemsPath());
    
    public SuppliedItemsFrame() {

        initComponents();
        setSize(900, 700);
        lblNoMatchMsg.setVisible(false);
        loadSuppliedItemsTable();    
        
        ComboBoxDataLoader readFile = new ComboBoxDataLoader();
        
        // Call the fillComboBox method to populate cbxItemName
        readFile.fillFilterSupplierCodeComboBox(cbxSupplier); 
        readFile.fillFilterItemCodeComboBox(cbxSuppliedItem);
                
        jPanelFilterSuppliedItems.setVisible(true);
        jPanelModifySuppliedItems.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        btnSignOut = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnItems = new javax.swing.JButton();
        btnSuppliers = new javax.swing.JButton();
        btnSuppliedItems = new javax.swing.JButton();
        btnModifySuppliedItem = new javax.swing.JButton();
        btnUpdateStock = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jPanelFilterSuppliedItems = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblItemCode = new javax.swing.JLabel();
        lblSupplierID = new javax.swing.JLabel();
        lblSellingPrice = new javax.swing.JLabel();
        btnFilterSuppliedItems = new javax.swing.JButton();
        txtMinCostPrice = new javax.swing.JTextField();
        btnLoadAllSuppliedItems = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMaxCostPrice = new javax.swing.JTextField();
        chkViewAllCostPrice = new javax.swing.JCheckBox();
        cbxSupplier = new javax.swing.JComboBox<>();
        cbxSuppliedItem = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollBar1 = new javax.swing.JScrollBar();
        lblNoMatchMsg = new javax.swing.JLabel();
        scrollPaneSuppliedItems = new javax.swing.JScrollPane();
        tblSuppliedItems = new javax.swing.JTable();
        jPanelModifySuppliedItems = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblItemCode2 = new javax.swing.JLabel();
        lblSupplierID2 = new javax.swing.JLabel();
        btnConfirmModifySuppliedItems = new javax.swing.JButton();
        btnLoadModifiedSuppliedItems = new javax.swing.JToggleButton();
        lblCostPrice4 = new javax.swing.JLabel();
        txtModifySuppliedItemCost = new javax.swing.JTextField();
        cbxModifySuppliedItems = new javax.swing.JComboBox<>();
        cbxModifySupplier = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(990, 535));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setPreferredSize(new java.awt.Dimension(4, 40));

        lblUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUser.setText("User: Cheah Thong Yau (Inventory Manager)");

        btnSignOut.setText("Sign Out");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(btnSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnItems.setText("Items");
        btnItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemsActionPerformed(evt);
            }
        });

        btnSuppliers.setText("Suppliers");
        btnSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppliersActionPerformed(evt);
            }
        });

        btnSuppliedItems.setText("Supplied Items");
        btnSuppliedItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppliedItemsActionPerformed(evt);
            }
        });

        btnModifySuppliedItem.setText("Modify Cost");
        btnModifySuppliedItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifySuppliedItemActionPerformed(evt);
            }
        });

        btnUpdateStock.setText("Update Stock");
        btnUpdateStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSuppliers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSuppliedItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnModifySuppliedItem)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnItems, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSuppliedItems, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModifySuppliedItem)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateStock, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setPreferredSize(new java.awt.Dimension(119, 50));

        lblTitle.setFont(new java.awt.Font("Bodoni MT Poster Compressed", 1, 24)); // NOI18N
        lblTitle.setText("ITEMS");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addContainerGap())
        );

        jPanelFilterSuppliedItems.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Enter Items Details");

        lblItemCode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblItemCode.setText("Item Code:");

        lblSupplierID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSupplierID.setText("Supplier ID:");

        lblSellingPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSellingPrice.setText("Cost Price:");

        btnFilterSuppliedItems.setText("Filter");
        btnFilterSuppliedItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterSuppliedItemsActionPerformed(evt);
            }
        });

        txtMinCostPrice.setText("0");
        txtMinCostPrice.setMinimumSize(new java.awt.Dimension(64, 25));
        txtMinCostPrice.setPreferredSize(new java.awt.Dimension(64, 25));
        txtMinCostPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinCostPriceActionPerformed(evt);
            }
        });

        btnLoadAllSuppliedItems.setText("Load All Items");
        btnLoadAllSuppliedItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadAllSuppliedItemsActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jLabel7.setText("Min:");

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jLabel8.setText("Max:");

        txtMaxCostPrice.setText("40.00");
        txtMaxCostPrice.setMinimumSize(new java.awt.Dimension(64, 25));
        txtMaxCostPrice.setPreferredSize(new java.awt.Dimension(64, 25));
        txtMaxCostPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxCostPriceActionPerformed(evt);
            }
        });

        chkViewAllCostPrice.setText("View All Cost Price");
        chkViewAllCostPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkViewAllCostPriceActionPerformed(evt);
            }
        });

        cbxSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSupplierActionPerformed(evt);
            }
        });

        cbxSuppliedItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxSuppliedItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSuppliedItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFilterSuppliedItemsLayout = new javax.swing.GroupLayout(jPanelFilterSuppliedItems);
        jPanelFilterSuppliedItems.setLayout(jPanelFilterSuppliedItemsLayout);
        jPanelFilterSuppliedItemsLayout.setHorizontalGroup(
            jPanelFilterSuppliedItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilterSuppliedItemsLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanelFilterSuppliedItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFilterSuppliedItemsLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addContainerGap(122, Short.MAX_VALUE))
                    .addGroup(jPanelFilterSuppliedItemsLayout.createSequentialGroup()
                        .addGroup(jPanelFilterSuppliedItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblItemCode))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelFilterSuppliedItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxSuppliedItem, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFilterSuppliedItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFilterSuppliedItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFilterSuppliedItemsLayout.createSequentialGroup()
                        .addComponent(lblSellingPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkViewAllCostPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelFilterSuppliedItemsLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMinCostPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaxCostPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelFilterSuppliedItemsLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanelFilterSuppliedItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFilterSuppliedItemsLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnFilterSuppliedItems, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLoadAllSuppliedItems, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFilterSuppliedItemsLayout.setVerticalGroup(
            jPanelFilterSuppliedItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFilterSuppliedItemsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanelFilterSuppliedItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplierID)
                    .addComponent(cbxSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanelFilterSuppliedItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemCode)
                    .addComponent(cbxSuppliedItem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelFilterSuppliedItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSellingPrice)
                    .addComponent(chkViewAllCostPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFilterSuppliedItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMinCostPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtMaxCostPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btnFilterSuppliedItems, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLoadAllSuppliedItems, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblNoMatchMsg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNoMatchMsg.setForeground(new java.awt.Color(255, 0, 0));
        lblNoMatchMsg.setText("No Matching Message");

        tblSuppliedItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Supplier ID", "Item ID", "Cost"
            }
        ));
        scrollPaneSuppliedItems.setViewportView(tblSuppliedItems);

        jPanelModifySuppliedItems.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Modify Items");

        lblItemCode2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblItemCode2.setText("Item Code:");

        lblSupplierID2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSupplierID2.setText("Supplier ID:");

        btnConfirmModifySuppliedItems.setText("Modify Item");
        btnConfirmModifySuppliedItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmModifySuppliedItemsActionPerformed(evt);
            }
        });

        btnLoadModifiedSuppliedItems.setText("Load Items");
        btnLoadModifiedSuppliedItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadModifiedSuppliedItemsActionPerformed(evt);
            }
        });

        lblCostPrice4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCostPrice4.setText("Cost Price:");

        txtModifySuppliedItemCost.setText("0");
        txtModifySuppliedItemCost.setMinimumSize(new java.awt.Dimension(64, 25));
        txtModifySuppliedItemCost.setPreferredSize(new java.awt.Dimension(64, 25));
        txtModifySuppliedItemCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModifySuppliedItemCostActionPerformed(evt);
            }
        });

        cbxModifySuppliedItems.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxModifySuppliedItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxModifySuppliedItemsActionPerformed(evt);
            }
        });

        cbxModifySupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxModifySupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxModifySupplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelModifySuppliedItemsLayout = new javax.swing.GroupLayout(jPanelModifySuppliedItems);
        jPanelModifySuppliedItems.setLayout(jPanelModifySuppliedItemsLayout);
        jPanelModifySuppliedItemsLayout.setHorizontalGroup(
            jPanelModifySuppliedItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModifySuppliedItemsLayout.createSequentialGroup()
                .addGroup(jPanelModifySuppliedItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModifySuppliedItemsLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel9))
                    .addGroup(jPanelModifySuppliedItemsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelModifySuppliedItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCostPrice4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblItemCode2)
                            .addComponent(lblSupplierID2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanelModifySuppliedItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxModifySupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxModifySuppliedItems, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModifySuppliedItemCost, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModifySuppliedItemsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelModifySuppliedItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModifySuppliedItemsLayout.createSequentialGroup()
                        .addComponent(btnConfirmModifySuppliedItems)
                        .addGap(8, 8, 8))
                    .addComponent(btnLoadModifiedSuppliedItems, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );
        jPanelModifySuppliedItemsLayout.setVerticalGroup(
            jPanelModifySuppliedItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModifySuppliedItemsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addGap(33, 33, 33)
                .addGroup(jPanelModifySuppliedItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplierID2)
                    .addComponent(cbxModifySupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelModifySuppliedItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemCode2)
                    .addComponent(cbxModifySuppliedItems, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanelModifySuppliedItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModifySuppliedItemCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCostPrice4))
                .addGap(43, 43, 43)
                .addComponent(btnConfirmModifySuppliedItems, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLoadModifiedSuppliedItems, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1205, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(lblNoMatchMsg)
                                                .addGap(294, 294, 294))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(scrollPaneSuppliedItems, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                        .addComponent(jPanelFilterSuppliedItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanelModifySuppliedItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(scrollPaneSuppliedItems, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblNoMatchMsg)
                                .addGap(0, 83, Short.MAX_VALUE))
                            .addComponent(jPanelFilterSuppliedItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelModifySuppliedItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void btnSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppliersActionPerformed
        SupplierFrame it = new SupplierFrame();
        it.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnSuppliersActionPerformed

    private void btnItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemsActionPerformed
        ItemsFrame it = new ItemsFrame();
        it.setVisible(true);
        this.hide();
        
    }//GEN-LAST:event_btnItemsActionPerformed
    private void cbxSuppliedItemActionPerformed(java.awt.event.ActionEvent evt){
        
    }
    private void txtModifySuppliedItemCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModifySuppliedItemCostActionPerformed
   
    }//GEN-LAST:event_txtModifySuppliedItemCostActionPerformed
    private void txtMaxCostPriceActionPerformed(java.awt.event.ActionEvent evt){
        
    }
    private void btnConfirmModifySuppliedItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmModifySuppliedItemsActionPerformed
        String itemCode = (String) cbxModifySuppliedItems.getSelectedItem();
        String supplierCode = (String) cbxModifySupplier.getSelectedItem();
        String costStr = txtModifySuppliedItemCost.getText().trim();
        
        supplierList.clear();
        supplierManager.read(supplierList, Supplier.class);
        suppliedItemsList.clear();
        suppliedItemsManager.read(suppliedItemsList, SuppliedItems.class);
        
        // Validation checks
        if(supplierCode.equals("NONE") || itemCode.equals("NONE")){
            JOptionPane.showMessageDialog(this, "Select both supplier & item to modify.");
            return;     
        }

        double cost;

        try{
            cost = Double.parseDouble(costStr);
            if (cost < 0) { // Check for negative cost or selling price
                JOptionPane.showMessageDialog(this, "Cost cannot be negative.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Cost must be valid numbers.","Input Error",JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean success = SuppliedItems.updateCost(suppliedItemsList, supplierCode, itemCode,cost);
        
        if (success) {
            loadSuppliedItemsTable();
            JOptionPane.showMessageDialog(this, "Item modified successfully!");
        } else {
            JOptionPane.showMessageDialog(this, "Supplied Item does not exist.","Input Error",JOptionPane.ERROR_MESSAGE);
        }
                   
    }//GEN-LAST:event_btnConfirmModifySuppliedItemsActionPerformed

    private void btnLoadModifiedSuppliedItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadModifiedSuppliedItemsActionPerformed
        loadSuppliedItemsTable();
    }//GEN-LAST:event_btnLoadModifiedSuppliedItemsActionPerformed
    private void cbxSupplierActionPerformed(java.awt.event.ActionEvent evt){
        
    }
    private void cbxModifySuppliedItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxModifySupplierActionPerformed
        String selectedSupplierCode = (String) cbxModifySupplier.getSelectedItem();
        String selectedItemCode = (String) cbxModifySuppliedItems.getSelectedItem(); // Get the selected item

        if (selectedSupplierCode != null && selectedItemCode != null) {
            SuppliedItems selectedSuppliedItem = SuppliedItems.findSuppliedItem(suppliedItemsList, selectedSupplierCode, selectedItemCode);
            if (selectedSuppliedItem != null) {
                txtModifySuppliedItemCost.setText(String.valueOf(selectedSuppliedItem.getCost()));
            } else {
                txtModifySuppliedItemCost.setText(""); // Clear the field if no match
            }
        }      
    }//GEN-LAST:event_cbxModifySupplierActionPerformed

    private void btnSuppliedItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppliedItemsActionPerformed
        loadSuppliedItemsTable();
        jPanelFilterSuppliedItems.setVisible(true);
        jPanelModifySuppliedItems.setVisible(false);
    }//GEN-LAST:event_btnSuppliedItemsActionPerformed

    private void chkViewAllCostPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkViewAllCostPriceActionPerformed
        if (chkViewAllCostPrice.isSelected()) {
            txtMinCostPrice.setEnabled(false);
            txtMaxCostPrice.setEnabled(false);
        } else {
            txtMinCostPrice.setEnabled(true);
            txtMaxCostPrice.setEnabled(true);
        }
    }//GEN-LAST:event_chkViewAllCostPriceActionPerformed

    private void txtMinCostPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinCostPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinCostPriceActionPerformed

    private void btnLoadAllSuppliedItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadAllSuppliedItemsActionPerformed
        loadSuppliedItemsTable();
    }//GEN-LAST:event_btnLoadAllSuppliedItemsActionPerformed

    private void btnFilterSuppliedItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterSuppliedItemsActionPerformed

        String itemCodeInput = (String) cbxSuppliedItem.getSelectedItem();
        String supplierIDInput = (String) cbxSupplier.getSelectedItem();

        boolean viewAllCostPrice = chkViewAllCostPrice.isSelected();
        String minCostPriceInput = txtMinCostPrice.getText();
        String maxCostPriceInput = txtMaxCostPrice.getText();
        

        List<String> matchingRows = SuppliedItems.filterSuppliedItemsTable(
            supplierIDInput,
            itemCodeInput,
            viewAllCostPrice,
            minCostPriceInput,
            maxCostPriceInput);

        DefaultTableModel tableModel = (DefaultTableModel) tblSuppliedItems.getModel();

        tableModel.setRowCount(0);

        if (!matchingRows.isEmpty()) {
            for(String row : matchingRows) {
                String[] parts = row.split(",");
                String supplierCode = parts[0].trim();
                String itemCode = parts[1].trim();
                String cost = (parts.length > 2) ? parts[2].trim() : ""; 
                tableModel.addRow(new Object[]{supplierCode,itemCode,cost});

            }
            lblNoMatchMsg.setVisible(false);
        } else {
            lblNoMatchMsg.setVisible(true);
            lblNoMatchMsg.setText("No Matching Items");
        }
    }//GEN-LAST:event_btnFilterSuppliedItemsActionPerformed

    private void cbxModifySupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxModifySuppliedItemsActionPerformed
        String selectedSupplierCode = (String) cbxModifySupplier.getSelectedItem();
        String selectedItemCode = (String) cbxModifySuppliedItems.getSelectedItem();

        if (selectedSupplierCode != null && selectedItemCode != null) {
            SuppliedItems selectedSuppliedItem = SuppliedItems.findSuppliedItem(suppliedItemsList, selectedSupplierCode, selectedItemCode);
            if (selectedSuppliedItem != null) {
                txtModifySuppliedItemCost.setText(String.valueOf(selectedSuppliedItem.getCost()));
            } else {
                txtModifySuppliedItemCost.setText(""); // Clear the field if no match
            }
        }
    }//GEN-LAST:event_cbxModifySuppliedItemsActionPerformed

    private void btnModifySuppliedItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifySuppliedItemActionPerformed
        loadSuppliedItemsTable();
        jPanelFilterSuppliedItems.setVisible(false);
        jPanelModifySuppliedItems.setVisible(true);
        ComboBoxDataLoader readFile = new ComboBoxDataLoader();
        readFile.fillModifySupplierCodeComboBox(cbxModifySupplier); 
        readFile.fillModifyItemCodeComboBox(cbxModifySuppliedItems);
    }//GEN-LAST:event_btnModifySuppliedItemActionPerformed

    private void btnUpdateStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStockActionPerformed
        UpdateStockFrame it = new UpdateStockFrame();
        it.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnUpdateStockActionPerformed


    private void loadSuppliedItemsTable(){
        suppliedItemsList.clear();
        // Load items from the file into the ArrayList
        SuppliedItems.rebuildSuppliedItems();
        suppliedItemsManager.read(suppliedItemsList, SuppliedItems.class);
        // Add items to the JTable
        DefaultTableModel model = (DefaultTableModel) tblSuppliedItems.getModel();
        model.setRowCount(0);  // Clear existing rows

        for (SuppliedItems item : suppliedItemsList) {
            model.addRow(new Object[]{
                item.getSupplierID(), 
                item.getItemCode(), 
                item.getCost()
            });
        }

        // Optionally, handle case when no items are found
        if (suppliedItemsList.isEmpty()) {
            lblNoMatchMsg.setVisible(true); // Show no items found message
        } else {
            lblNoMatchMsg.setVisible(false); // Hide the message
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuppliedItemsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmModifySuppliedItems;
    private javax.swing.JButton btnFilterSuppliedItems;
    private javax.swing.JButton btnItems;
    private javax.swing.JToggleButton btnLoadAllSuppliedItems;
    private javax.swing.JToggleButton btnLoadModifiedSuppliedItems;
    private javax.swing.JButton btnModifySuppliedItem;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JButton btnSuppliedItems;
    private javax.swing.JButton btnSuppliers;
    private javax.swing.JButton btnUpdateStock;
    private javax.swing.JComboBox<String> cbxModifySuppliedItems;
    private javax.swing.JComboBox<String> cbxModifySupplier;
    private javax.swing.JComboBox<String> cbxSuppliedItem;
    private javax.swing.JComboBox<String> cbxSupplier;
    private javax.swing.JCheckBox chkViewAllCostPrice;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelFilterSuppliedItems;
    private javax.swing.JPanel jPanelModifySuppliedItems;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCostPrice4;
    private javax.swing.JLabel lblItemCode;
    private javax.swing.JLabel lblItemCode2;
    private javax.swing.JLabel lblNoMatchMsg;
    private javax.swing.JLabel lblSellingPrice;
    private javax.swing.JLabel lblSupplierID;
    private javax.swing.JLabel lblSupplierID2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JScrollPane scrollPaneSuppliedItems;
    private javax.swing.JTable tblSuppliedItems;
    private javax.swing.JTextField txtMaxCostPrice;
    private javax.swing.JTextField txtMinCostPrice;
    private javax.swing.JTextField txtModifySuppliedItemCost;
    // End of variables declaration//GEN-END:variables
}
