/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventory.manager;


import java.util.List;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ItemsFrame extends javax.swing.JFrame {

    private ArrayList<Item> itemList = new ArrayList<>();
    private ArrayList<Supplier> supplierList = new ArrayList<>();
    private static FileManager<Supplier> supplierManager = new FileManager<>("C:\\Users\\User\\OneDrive\\Documents\\APU\\Java Y2\\NetBeansProjects\\Inventory Manager\\src\\inventory\\manager\\Supplier.txt");
    private static FileManager<Item> itemManager = new FileManager<>("C:\\Users\\User\\OneDrive\\Documents\\APU\\Java Y2\\NetBeansProjects\\Inventory Manager\\src\\inventory\\manager\\Inventory.txt");
    
    public ItemsFrame() {
        initComponents();
        setSize(1250, 700);
        lblNoMatchMsg.setVisible(false);
        loadItemsTable();
        
        // Empty comboBox and add comparison operator 
        cbxComparisonOperator.removeAllItems();
        cbxComparisonOperator.addItem("ALL");
        cbxComparisonOperator.addItem("==");
        cbxComparisonOperator.addItem(">");
        cbxComparisonOperator.addItem(">=");
        cbxComparisonOperator.addItem("<");
        cbxComparisonOperator.addItem("<=");      
        
        ComboBoxDataLoader readFile = new ComboBoxDataLoader();
        
        // Call the fillComboBox method to populate cbxItemName
        readFile.fillItemNameComboBox(cbxItemName); 
        readFile.fillCategoryComboBox(cbxCategory);
                
        jPanelAddItems.setVisible(false);
        jPanelFilterItems.setVisible(true);
        jPanelModifyItems.setVisible(false);
        jPanelDeleteItems.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        btnSignOut = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnItems = new javax.swing.JButton();
        btnSuppliers = new javax.swing.JButton();
        btnAddItems = new javax.swing.JButton();
        btnDeleteItem = new javax.swing.JButton();
        btnModifyItems = new javax.swing.JButton();
        btnSuppliedItems = new javax.swing.JButton();
        btnUpdateStocks = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jPanelFilterItems = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblItemCode = new javax.swing.JLabel();
        lblItemName = new javax.swing.JLabel();
        lblSupplierID = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        lblSellingPrice = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        txtItemCode = new javax.swing.JTextField();
        txtSupplierID = new javax.swing.JTextField();
        txtQuantityValue = new javax.swing.JTextField();
        cbxItemName = new javax.swing.JComboBox<>();
        btnFilterItems = new javax.swing.JButton();
        txtMinSellingPrice = new javax.swing.JTextField();
        cbxCategory = new javax.swing.JComboBox<>();
        btnLoadAllItems = new javax.swing.JToggleButton();
        cbxComparisonOperator = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMaxSellingPrice = new javax.swing.JTextField();
        chkViewAllSellingPrice = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollBar1 = new javax.swing.JScrollBar();
        lblNoMatchMsg = new javax.swing.JLabel();
        jPanelAddItems = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblItemCode1 = new javax.swing.JLabel();
        lblItemName1 = new javax.swing.JLabel();
        lblSupplierID1 = new javax.swing.JLabel();
        lblQuantity1 = new javax.swing.JLabel();
        lblCategory1 = new javax.swing.JLabel();
        txtAddItemCode = new javax.swing.JTextField();
        btnConfirmAddItems = new javax.swing.JButton();
        btnLoadAddedItems = new javax.swing.JToggleButton();
        txtAddCategory = new javax.swing.JTextField();
        txtAddItemName = new javax.swing.JTextField();
        txtAddQuantity = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstSuppliers = new javax.swing.JList<>();
        lblCostPrice2 = new javax.swing.JLabel();
        txtAddSellingPrice = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItemsTable = new javax.swing.JTable();
        jPanelModifyItems = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblItemCode2 = new javax.swing.JLabel();
        lblItemName2 = new javax.swing.JLabel();
        lblSupplierID2 = new javax.swing.JLabel();
        lblQuantity2 = new javax.swing.JLabel();
        lblCategory2 = new javax.swing.JLabel();
        btnConfirmModifyItems = new javax.swing.JButton();
        btnLoadModifiedItems = new javax.swing.JToggleButton();
        txtModifyCategory = new javax.swing.JTextField();
        txtModifyItemName = new javax.swing.JTextField();
        txtModifyQuantity = new javax.swing.JTextField();
        lblCostPrice4 = new javax.swing.JLabel();
        txtModifySellingPrice = new javax.swing.JTextField();
        txtModifySupplier = new javax.swing.JTextField();
        cbxItemCode = new javax.swing.JComboBox<>();
        jPanelDeleteItems = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lblItemCode3 = new javax.swing.JLabel();
        lblItemName3 = new javax.swing.JLabel();
        lblSupplierID3 = new javax.swing.JLabel();
        lblCategory3 = new javax.swing.JLabel();
        btnConfirmDeleteItems = new javax.swing.JButton();
        btnLoadUpdatedItems = new javax.swing.JToggleButton();
        txtDeleteCategory = new javax.swing.JTextField();
        txtDeleteItemName = new javax.swing.JTextField();
        lblCostPrice6 = new javax.swing.JLabel();
        txtDeleteSellingPrice = new javax.swing.JTextField();
        txtDeleteSupplier = new javax.swing.JTextField();
        cbxItemCode1 = new javax.swing.JComboBox<>();
        lblQuantity3 = new javax.swing.JLabel();
        txtDeleteQuantity = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(990, 535));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setPreferredSize(new java.awt.Dimension(4, 40));

        lblUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUser.setText("User: Cheah Thong Yau (Inventory Manager)");

        btnSignOut.setText("Sign Out");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(btnSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnItems.setText("Items");
        btnItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemsActionPerformed(evt);
            }
        });

        btnSuppliers.setText("Suppliers");
        btnSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppliersActionPerformed(evt);
            }
        });

        btnAddItems.setText("Add Items");
        btnAddItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemsActionPerformed(evt);
            }
        });

        btnDeleteItem.setText("Delete Items");
        btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemActionPerformed(evt);
            }
        });

        btnModifyItems.setText("Modify Items");
        btnModifyItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyItemsActionPerformed(evt);
            }
        });

        btnSuppliedItems.setText("Supplied Items");
        btnSuppliedItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppliedItemsActionPerformed(evt);
            }
        });

        btnUpdateStocks.setText("Update Stock");
        btnUpdateStocks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStocksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModifyItems, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddItems, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSuppliers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSuppliedItems, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateStocks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnItems, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnAddItems)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModifyItems)
                .addGap(18, 18, 18)
                .addComponent(btnSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSuppliedItems, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateStocks, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setPreferredSize(new java.awt.Dimension(119, 50));

        lblTitle.setFont(new java.awt.Font("Bodoni MT Poster Compressed", 1, 24)); // NOI18N
        lblTitle.setText("ITEMS");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addContainerGap())
        );

        jPanelFilterItems.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Enter Items Details");

        lblItemCode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblItemCode.setText("Item Code:");

        lblItemName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblItemName.setText("Item Name:");

        lblSupplierID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSupplierID.setText("Supplier ID:");

        lblQuantity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQuantity.setText("Quantity:");

        lblSellingPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSellingPrice.setText("Selling Price:");

        lblCategory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCategory.setText("Category: ");

        txtItemCode.setPreferredSize(new java.awt.Dimension(64, 25));
        txtItemCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemCodeActionPerformed(evt);
            }
        });

        txtSupplierID.setMinimumSize(new java.awt.Dimension(64, 25));
        txtSupplierID.setPreferredSize(new java.awt.Dimension(64, 25));
        txtSupplierID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierIDActionPerformed(evt);
            }
        });

        txtQuantityValue.setText("0");
        txtQuantityValue.setMinimumSize(new java.awt.Dimension(64, 25));
        txtQuantityValue.setPreferredSize(new java.awt.Dimension(64, 25));
        txtQuantityValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityValueActionPerformed(evt);
            }
        });

        cbxItemName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxItemNameActionPerformed(evt);
            }
        });

        btnFilterItems.setText("Filter");
        btnFilterItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterItemsActionPerformed(evt);
            }
        });

        txtMinSellingPrice.setText("0");
        txtMinSellingPrice.setMinimumSize(new java.awt.Dimension(64, 25));
        txtMinSellingPrice.setPreferredSize(new java.awt.Dimension(64, 25));
        txtMinSellingPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinSellingPriceActionPerformed(evt);
            }
        });

        cbxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoryActionPerformed(evt);
            }
        });

        btnLoadAllItems.setText("Load All Items");
        btnLoadAllItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadAllItemsActionPerformed(evt);
            }
        });

        cbxComparisonOperator.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxComparisonOperator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxComparisonOperatorActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jLabel7.setText("Min:");

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jLabel8.setText("Max:");

        txtMaxSellingPrice.setText("40.00");
        txtMaxSellingPrice.setMinimumSize(new java.awt.Dimension(64, 25));
        txtMaxSellingPrice.setPreferredSize(new java.awt.Dimension(64, 25));
        txtMaxSellingPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxSellingPriceActionPerformed(evt);
            }
        });

        chkViewAllSellingPrice.setText("View All Selling Price");
        chkViewAllSellingPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkViewAllSellingPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFilterItemsLayout = new javax.swing.GroupLayout(jPanelFilterItems);
        jPanelFilterItems.setLayout(jPanelFilterItemsLayout);
        jPanelFilterItemsLayout.setHorizontalGroup(
            jPanelFilterItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilterItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFilterItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFilterItemsLayout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(jPanelFilterItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFilterItemsLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2))
                            .addGroup(jPanelFilterItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanelFilterItemsLayout.createSequentialGroup()
                                    .addComponent(lblItemName)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFilterItemsLayout.createSequentialGroup()
                                    .addComponent(lblItemCode)
                                    .addGap(55, 55, 55)
                                    .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelFilterItemsLayout.createSequentialGroup()
                                .addGroup(jPanelFilterItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxComparisonOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblQuantity)
                                    .addComponent(lblCategory))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelFilterItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxCategory, 0, 123, Short.MAX_VALUE)
                                    .addComponent(txtQuantityValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(jPanelFilterItemsLayout.createSequentialGroup()
                        .addComponent(lblSellingPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkViewAllSellingPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelFilterItemsLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnFilterItems, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelFilterItemsLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMinSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaxSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFilterItemsLayout.createSequentialGroup()
                        .addComponent(lblSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFilterItemsLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnLoadAllItems, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelFilterItemsLayout.setVerticalGroup(
            jPanelFilterItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFilterItemsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanelFilterItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblItemCode)
                    .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFilterItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItemName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFilterItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCategory)
                    .addComponent(cbxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQuantity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFilterItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxComparisonOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantityValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelFilterItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSellingPrice)
                    .addComponent(chkViewAllSellingPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFilterItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMinSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtMaxSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanelFilterItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplierID)
                    .addComponent(txtSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnFilterItems, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLoadAllItems, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        lblNoMatchMsg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNoMatchMsg.setForeground(new java.awt.Color(255, 0, 0));
        lblNoMatchMsg.setText("No Matching Message");

        jPanelAddItems.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Add Items");

        lblItemCode1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblItemCode1.setText("Item Code:");

        lblItemName1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblItemName1.setText("Item Name:");

        lblSupplierID1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSupplierID1.setText("Supplier ID:");

        lblQuantity1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQuantity1.setText("Quantity:");

        lblCategory1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCategory1.setText("Category: ");

        txtAddItemCode.setPreferredSize(new java.awt.Dimension(64, 25));
        txtAddItemCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddItemCodeActionPerformed(evt);
            }
        });

        btnConfirmAddItems.setText("Add Item");
        btnConfirmAddItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmAddItemsActionPerformed(evt);
            }
        });

        btnLoadAddedItems.setText("Load Items");
        btnLoadAddedItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadAddedItemsActionPerformed(evt);
            }
        });

        txtAddCategory.setPreferredSize(new java.awt.Dimension(64, 25));
        txtAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddCategoryActionPerformed(evt);
            }
        });

        txtAddItemName.setPreferredSize(new java.awt.Dimension(64, 25));
        txtAddItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddItemNameActionPerformed(evt);
            }
        });

        txtAddQuantity.setText("0");
        txtAddQuantity.setMinimumSize(new java.awt.Dimension(64, 25));
        txtAddQuantity.setPreferredSize(new java.awt.Dimension(64, 25));
        txtAddQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddQuantityActionPerformed(evt);
            }
        });

        lstSuppliers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "S001", "S002", "S003", "S004", "S005", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstSuppliers);

        lblCostPrice2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCostPrice2.setText("Selling Price:");

        txtAddSellingPrice.setText("0");
        txtAddSellingPrice.setMinimumSize(new java.awt.Dimension(64, 25));
        txtAddSellingPrice.setPreferredSize(new java.awt.Dimension(64, 25));
        txtAddSellingPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddSellingPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAddItemsLayout = new javax.swing.GroupLayout(jPanelAddItems);
        jPanelAddItems.setLayout(jPanelAddItemsLayout);
        jPanelAddItemsLayout.setHorizontalGroup(
            jPanelAddItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddItemsLayout.createSequentialGroup()
                .addGroup(jPanelAddItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAddItemsLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanelAddItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAddItemsLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4))
                            .addComponent(lblItemCode1)
                            .addComponent(lblCategory1)
                            .addComponent(lblItemName1)
                            .addComponent(lblQuantity1)))
                    .addGroup(jPanelAddItemsLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnConfirmAddItems, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAddItemsLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnLoadAddedItems, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAddItemsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelAddItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanelAddItemsLayout.createSequentialGroup()
                                .addComponent(lblSupplierID1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelAddItemsLayout.createSequentialGroup()
                                .addGroup(jPanelAddItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtAddItemCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAddCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAddItemName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAddQuantity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAddItemsLayout.createSequentialGroup()
                                .addComponent(lblCostPrice2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(28, 28, 28)
                                .addComponent(txtAddSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanelAddItemsLayout.setVerticalGroup(
            jPanelAddItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddItemsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanelAddItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemCode1)
                    .addComponent(txtAddItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAddItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemName1)
                    .addComponent(txtAddItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAddItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategory1)
                    .addComponent(txtAddCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAddItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity1)
                    .addComponent(txtAddQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAddItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCostPrice2)
                    .addComponent(txtAddSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAddItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSupplierID1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnConfirmAddItems, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLoadAddedItems, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        tblItemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Item Code", "Item Name", "Category", "Quantity", "Selling Price", "SupplierID"
            }
        ));
        jScrollPane1.setViewportView(tblItemsTable);

        jScrollPane4.setViewportView(jScrollPane1);

        jPanelModifyItems.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Modify Items");

        lblItemCode2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblItemCode2.setText("Item Code:");

        lblItemName2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblItemName2.setText("Item Name:");

        lblSupplierID2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSupplierID2.setText("Supplier ID:");

        lblQuantity2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQuantity2.setText("Quantity:");

        lblCategory2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCategory2.setText("Category: ");

        btnConfirmModifyItems.setText("Modify Item");
        btnConfirmModifyItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmModifyItemsActionPerformed(evt);
            }
        });

        btnLoadModifiedItems.setText("Load Items");
        btnLoadModifiedItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadModifiedItemsActionPerformed(evt);
            }
        });

        txtModifyCategory.setPreferredSize(new java.awt.Dimension(64, 25));
        txtModifyCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModifyCategoryActionPerformed(evt);
            }
        });

        txtModifyItemName.setPreferredSize(new java.awt.Dimension(64, 25));
        txtModifyItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModifyItemNameActionPerformed(evt);
            }
        });

        txtModifyQuantity.setText("0");
        txtModifyQuantity.setMinimumSize(new java.awt.Dimension(64, 25));
        txtModifyQuantity.setPreferredSize(new java.awt.Dimension(64, 25));
        txtModifyQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModifyQuantityActionPerformed(evt);
            }
        });

        lblCostPrice4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCostPrice4.setText("Selling Price:");

        txtModifySellingPrice.setText("0");
        txtModifySellingPrice.setMinimumSize(new java.awt.Dimension(64, 25));
        txtModifySellingPrice.setPreferredSize(new java.awt.Dimension(64, 25));
        txtModifySellingPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModifySellingPriceActionPerformed(evt);
            }
        });

        txtModifySupplier.setPreferredSize(new java.awt.Dimension(64, 25));
        txtModifySupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModifySupplierActionPerformed(evt);
            }
        });

        cbxItemCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxItemCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxItemCodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelModifyItemsLayout = new javax.swing.GroupLayout(jPanelModifyItems);
        jPanelModifyItems.setLayout(jPanelModifyItemsLayout);
        jPanelModifyItemsLayout.setHorizontalGroup(
            jPanelModifyItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModifyItemsLayout.createSequentialGroup()
                .addGroup(jPanelModifyItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModifyItemsLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanelModifyItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelModifyItemsLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel9))
                            .addComponent(lblItemCode2)
                            .addComponent(lblCategory2)
                            .addComponent(lblItemName2)
                            .addComponent(lblQuantity2)))
                    .addGroup(jPanelModifyItemsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelModifyItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelModifyItemsLayout.createSequentialGroup()
                                .addComponent(lblSupplierID2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(txtModifySupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelModifyItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelModifyItemsLayout.createSequentialGroup()
                                    .addGroup(jPanelModifyItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelModifyItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtModifyCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtModifyItemName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtModifyQuantity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(cbxItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(1, 1, 1))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelModifyItemsLayout.createSequentialGroup()
                                    .addComponent(lblCostPrice4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtModifySellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanelModifyItemsLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanelModifyItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModifyItemsLayout.createSequentialGroup()
                                .addComponent(btnConfirmModifyItems)
                                .addGap(8, 8, 8))
                            .addComponent(btnLoadModifiedItems, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanelModifyItemsLayout.setVerticalGroup(
            jPanelModifyItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModifyItemsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addGap(23, 23, 23)
                .addGroup(jPanelModifyItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemCode2)
                    .addComponent(cbxItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelModifyItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemName2)
                    .addComponent(txtModifyItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelModifyItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategory2)
                    .addComponent(txtModifyCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelModifyItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity2)
                    .addComponent(txtModifyQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelModifyItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCostPrice4)
                    .addComponent(txtModifySellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelModifyItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSupplierID2)
                    .addComponent(txtModifySupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnConfirmModifyItems, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLoadModifiedItems, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDeleteItems.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Delete Items");

        lblItemCode3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblItemCode3.setText("Item Code:");

        lblItemName3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblItemName3.setText("Item Name:");

        lblSupplierID3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSupplierID3.setText("Supplier ID:");

        lblCategory3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCategory3.setText("Category: ");

        btnConfirmDeleteItems.setText("Delete Item");
        btnConfirmDeleteItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmDeleteItemsActionPerformed(evt);
            }
        });

        btnLoadUpdatedItems.setText("Load Items");
        btnLoadUpdatedItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadUpdatedItemsActionPerformed(evt);
            }
        });

        txtDeleteCategory.setPreferredSize(new java.awt.Dimension(64, 25));
        txtDeleteCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeleteCategoryActionPerformed(evt);
            }
        });

        txtDeleteItemName.setPreferredSize(new java.awt.Dimension(64, 25));
        txtDeleteItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeleteItemNameActionPerformed(evt);
            }
        });

        lblCostPrice6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCostPrice6.setText("Selling Price:");

        txtDeleteSellingPrice.setText("0");
        txtDeleteSellingPrice.setMinimumSize(new java.awt.Dimension(64, 25));
        txtDeleteSellingPrice.setPreferredSize(new java.awt.Dimension(64, 25));
        txtDeleteSellingPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeleteSellingPriceActionPerformed(evt);
            }
        });

        txtDeleteSupplier.setPreferredSize(new java.awt.Dimension(64, 25));
        txtDeleteSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeleteSupplierActionPerformed(evt);
            }
        });

        cbxItemCode1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxItemCode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxItemCode1ActionPerformed(evt);
            }
        });

        lblQuantity3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQuantity3.setText("Quantity:");

        txtDeleteQuantity.setText("0");
        txtDeleteQuantity.setMinimumSize(new java.awt.Dimension(64, 25));
        txtDeleteQuantity.setPreferredSize(new java.awt.Dimension(64, 25));
        txtDeleteQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeleteQuantityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDeleteItemsLayout = new javax.swing.GroupLayout(jPanelDeleteItems);
        jPanelDeleteItems.setLayout(jPanelDeleteItemsLayout);
        jPanelDeleteItemsLayout.setHorizontalGroup(
            jPanelDeleteItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeleteItemsLayout.createSequentialGroup()
                .addGroup(jPanelDeleteItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDeleteItemsLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanelDeleteItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDeleteItemsLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel10))
                            .addComponent(lblItemCode3)
                            .addComponent(lblItemName3)
                            .addComponent(lblCategory3)))
                    .addGroup(jPanelDeleteItemsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelDeleteItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDeleteItemsLayout.createSequentialGroup()
                                .addComponent(lblSupplierID3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(txtDeleteSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelDeleteItemsLayout.createSequentialGroup()
                                .addComponent(lblQuantity3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelDeleteItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelDeleteItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtDeleteCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                        .addComponent(txtDeleteItemName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(cbxItemCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDeleteQuantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDeleteItemsLayout.createSequentialGroup()
                                .addComponent(lblCostPrice6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDeleteSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDeleteItemsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelDeleteItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDeleteItemsLayout.createSequentialGroup()
                        .addComponent(btnConfirmDeleteItems)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDeleteItemsLayout.createSequentialGroup()
                        .addComponent(btnLoadUpdatedItems, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
        );
        jPanelDeleteItemsLayout.setVerticalGroup(
            jPanelDeleteItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeleteItemsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addGap(23, 23, 23)
                .addGroup(jPanelDeleteItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemCode3)
                    .addComponent(cbxItemCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDeleteItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemName3)
                    .addComponent(txtDeleteItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDeleteItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategory3)
                    .addComponent(txtDeleteCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDeleteItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity3)
                    .addComponent(txtDeleteQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDeleteItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCostPrice6)
                    .addComponent(txtDeleteSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDeleteItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSupplierID3)
                    .addComponent(txtDeleteSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnConfirmDeleteItems, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLoadUpdatedItems, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 2134, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1976, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblNoMatchMsg))
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanelFilterItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelAddItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelModifyItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelDeleteItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 7, Short.MAX_VALUE))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAddItems, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblNoMatchMsg)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(jPanelModifyItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDeleteItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelFilterItems, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel3, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkViewAllSellingPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkViewAllSellingPriceActionPerformed
        if (chkViewAllSellingPrice.isSelected()) {
            txtMinSellingPrice.setEnabled(false);
            txtMaxSellingPrice.setEnabled(false);
        } else {
            txtMinSellingPrice.setEnabled(true);
            txtMaxSellingPrice.setEnabled(true);
        }
    }//GEN-LAST:event_chkViewAllSellingPriceActionPerformed

    private void txtMaxSellingPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxSellingPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxSellingPriceActionPerformed

    private void cbxComparisonOperatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxComparisonOperatorActionPerformed
        // Get current selected operator
        String selectedOperator = (String) cbxComparisonOperator.getSelectedItem();

        if ("ALL".equals(selectedOperator)) {
            txtQuantityValue.setText("");
            txtQuantityValue.setEnabled(false);
        } else {
            txtQuantityValue.setEnabled(true);
        }

    }//GEN-LAST:event_cbxComparisonOperatorActionPerformed

    private void btnLoadAllItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadAllItemsActionPerformed
        loadItemsTable();

    }//GEN-LAST:event_btnLoadAllItemsActionPerformed

    private void cbxCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoryActionPerformed

    }//GEN-LAST:event_cbxCategoryActionPerformed

    private void txtMinSellingPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinSellingPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinSellingPriceActionPerformed

    private void btnFilterItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterItemsActionPerformed

        String itemCodeInput = txtItemCode.getText();
        String itemNameInput = (String) cbxItemName.getSelectedItem();
        String categoryInput = (String) cbxCategory.getSelectedItem();
        String comparisonOperatorInput = (String) cbxComparisonOperator.getSelectedItem();
        String quantityValueInput = txtQuantityValue.getText();

        boolean viewAllSellingPrice = chkViewAllSellingPrice.isSelected();
        String minSellingPriceInput = txtMinSellingPrice.getText();
        String maxSellingrPiceInput = txtMaxSellingPrice.getText();

        String supplierIDInput = txtSupplierID.getText();

        List<String> matchingRows = Item.filterItemsTable(
            itemCodeInput,
            itemNameInput,
            categoryInput,
            comparisonOperatorInput,
            quantityValueInput,
            viewAllSellingPrice,
            minSellingPriceInput,
            maxSellingrPiceInput,
            supplierIDInput
        );

        DefaultTableModel tableModel = (DefaultTableModel) tblItemsTable.getModel();

        tableModel.setRowCount(0);

        if (!matchingRows.isEmpty()) {
            for(String row : matchingRows) {
                String[] parts = row.split(",");
                String itemCode = parts[0].trim();
                String itemName = parts[1].trim();
                String category = parts[2].trim();
                String quantity = parts[3].trim();
                String sellingPrice = parts[4].trim(); 
                String supplierCodes = String.join(";", Arrays.asList(parts).subList(5, parts.length));
                
                tableModel.addRow(new Object[]{itemCode,itemName,category, quantity,sellingPrice,supplierCodes});
                
            }
            lblNoMatchMsg.setVisible(false);
        } else {
            lblNoMatchMsg.setVisible(true);
            lblNoMatchMsg.setText("No Matching Items");
        }

    }//GEN-LAST:event_btnFilterItemsActionPerformed

    private void cbxItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxItemNameActionPerformed

    }//GEN-LAST:event_cbxItemNameActionPerformed

    private void txtQuantityValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityValueActionPerformed

    private void txtSupplierIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierIDActionPerformed

    private void txtItemCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemCodeActionPerformed

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void btnDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemActionPerformed
        loadItemsTable();
 
        ComboBoxDataLoader readFile = new ComboBoxDataLoader();
        readFile.fillItemCodeComboBox(cbxItemCode1);
        jPanelAddItems.setVisible(false);
        jPanelFilterItems.setVisible(false);
        jPanelModifyItems.setVisible(false);
        jPanelDeleteItems.setVisible(true);
        
    }//GEN-LAST:event_btnDeleteItemActionPerformed

    private void btnAddItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemsActionPerformed
        loadItemsTable();
        jPanelAddItems.setVisible(true);
        jPanelFilterItems.setVisible(false);
        jPanelModifyItems.setVisible(false);
        jPanelDeleteItems.setVisible(false);

        supplierManager.read(supplierList, Supplier.class);
        DefaultListModel<String> listModel = new DefaultListModel<>();
        for (Supplier supplier : supplierList) {
            listModel.addElement(supplier.getSupplierCode()); 
        }
        lstSuppliers.setModel(listModel);  // Set the model to the JList
    }//GEN-LAST:event_btnAddItemsActionPerformed

    private void btnSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppliersActionPerformed
        SupplierFrame it = new SupplierFrame();
        it.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnSuppliersActionPerformed

    private void btnItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemsActionPerformed
        loadItemsTable();
        jPanelAddItems.setVisible(false);
        jPanelFilterItems.setVisible(true);
        jPanelModifyItems.setVisible(false);
        jPanelDeleteItems.setVisible(false);
    }//GEN-LAST:event_btnItemsActionPerformed

    private void btnModifyItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyItemsActionPerformed
        loadItemsTable();
        ComboBoxDataLoader readFile = new ComboBoxDataLoader();
        readFile.fillItemCodeComboBox(cbxItemCode);
        jPanelAddItems.setVisible(false);
        jPanelFilterItems.setVisible(false);
        jPanelModifyItems.setVisible(true);
        jPanelDeleteItems.setVisible(false);
        
    }//GEN-LAST:event_btnModifyItemsActionPerformed

    private void btnConfirmModifyItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmModifyItemsActionPerformed
        String itemCode = (String) cbxItemCode.getSelectedItem();
        String itemName = txtModifyItemName.getText().trim();
        String category = txtModifyCategory.getText().trim();
        String quantityStr = txtModifyQuantity.getText().trim();
        String sellingPriceStr = txtModifySellingPrice.getText().trim();
        String supplierCodes = txtModifySupplier.getText().trim();
        
        supplierList.clear();
        supplierManager.read(supplierList, Supplier.class);
        itemList.clear();
        itemManager.read(itemList, Item.class);
        // Validation checks
        if(itemCode.equals("NONE")){
            JOptionPane.showMessageDialog(this, "Select an item to modify.");
            return;     
        }
        if(itemName.isEmpty() || category.isEmpty()){
            JOptionPane.showMessageDialog(this,"Name and Category cannot be blank.","Input Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        boolean nameExists = itemList.stream().anyMatch(item -> item.getItemName().equalsIgnoreCase(itemName)&&!item.getItemCode().equals(itemCode));
        if(nameExists){
            JOptionPane.showMessageDialog(this, "Item name already exists.","Input Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int quantity;
        double sellingPrice;
        
        try{
            quantity = Integer.parseInt(quantityStr);
            if (quantity < 0) { // Check for negative quantity
                JOptionPane.showMessageDialog(this, "Quantity cannot be negative.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Quantity must be an integer","Input Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            sellingPrice = Double.parseDouble(sellingPriceStr);
            if (sellingPrice < 0) { // Check for negative cost or selling price
                JOptionPane.showMessageDialog(this, "Cost and Selling Price cannot be negative.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Cost and Selling Price must be valid numbers.","Input Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
       
        ArrayList<String> suppliers = new ArrayList<>(Arrays.asList(supplierCodes.split(";")));

        boolean success = Item.modifyItem(itemList, supplierList, itemCode,itemName,category,quantity,sellingPrice,suppliers);
        
        if (success) {
            loadItemsTable();
            JOptionPane.showMessageDialog(this, "Item modified successfully!");
        } else {
            JOptionPane.showMessageDialog(this, "One or more supplier codes are invalid.","Input Error",JOptionPane.ERROR_MESSAGE);
        }
                   
    }//GEN-LAST:event_btnConfirmModifyItemsActionPerformed

    private void btnLoadModifiedItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadModifiedItemsActionPerformed
        loadItemsTable();
    }//GEN-LAST:event_btnLoadModifiedItemsActionPerformed

    private void txtModifyCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModifyCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModifyCategoryActionPerformed

    private void txtModifyItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModifyItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModifyItemNameActionPerformed

    private void txtModifyQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModifyQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModifyQuantityActionPerformed

    private void txtModifySellingPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModifySellingPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModifySellingPriceActionPerformed

    private void txtModifySupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModifySupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModifySupplierActionPerformed

    private void cbxItemCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxItemCodeActionPerformed
        String selectedItemCode = (String) cbxItemCode.getSelectedItem();

        Item selectedItem = Item.findItemByCode(itemList, selectedItemCode);
        if (selectedItem != null) {
            // Autofill the text fields with the supplier data
            txtModifyItemName.setText(selectedItem.getItemName());
            txtModifyCategory.setText(selectedItem.getDescription());
            txtModifyQuantity.setText(String.valueOf(selectedItem.getQuantity()));
            txtModifySellingPrice.setText(String.valueOf(selectedItem.getSellingPrice()));
            ArrayList<String> suppliedItems = selectedItem.getSupplierCodes();
            txtModifySupplier.setText(suppliedItems!= null? String.join(";", suppliedItems):"");
        }      
          
    }//GEN-LAST:event_cbxItemCodeActionPerformed

    private void btnConfirmDeleteItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmDeleteItemsActionPerformed
        String itemCode = (String) cbxItemCode1.getSelectedItem();
        
        supplierList.clear();
        supplierManager.read(supplierList, Supplier.class);
        itemList.clear();
        itemManager.read(itemList, Item.class);
        // Validation checks
        if(itemCode.equals("NONE")){
            JOptionPane.showMessageDialog(this, "Select an item to delete.");
            return;     
        }    
                
        itemList.clear();
        itemManager.read(itemList, Item.class);
        Item.deleteItem(itemList,supplierList,itemCode);
       
        loadItemsTable();
        JOptionPane.showMessageDialog(this, "Item deleted successfully!");

    }//GEN-LAST:event_btnConfirmDeleteItemsActionPerformed

    private void btnLoadUpdatedItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadUpdatedItemsActionPerformed
        loadItemsTable();
    }//GEN-LAST:event_btnLoadUpdatedItemsActionPerformed

    private void txtDeleteCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeleteCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeleteCategoryActionPerformed

    private void txtDeleteItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeleteItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeleteItemNameActionPerformed

    private void txtDeleteSellingPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeleteSellingPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeleteSellingPriceActionPerformed

    private void txtDeleteSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeleteSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeleteSupplierActionPerformed

    private void cbxItemCode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxItemCode1ActionPerformed
        String selectedItemCode = (String) cbxItemCode1.getSelectedItem();

        Item selectedItem = Item.findItemByCode(itemList, selectedItemCode);
        if (selectedItem != null) {
            // Autofill the text fields with the supplier data
            txtDeleteItemName.setText(selectedItem.getItemName());
            txtDeleteCategory.setText(selectedItem.getDescription());
            txtDeleteQuantity.setText(String.valueOf(selectedItem.getQuantity()));
            txtDeleteSellingPrice.setText(String.valueOf(selectedItem.getSellingPrice()));
            
            ArrayList<String> suppliedItemCodes = selectedItem.getSupplierCodes();
            txtDeleteSupplier.setText(suppliedItemCodes!= null? String.join(";", suppliedItemCodes):"");
        }
        
        txtDeleteItemName.setEnabled(false);
        txtDeleteCategory.setEnabled(false);
        txtDeleteQuantity.setEnabled(false);
        txtDeleteSellingPrice.setEnabled(false);
        txtDeleteSupplier.setEnabled(false);
        
    }//GEN-LAST:event_cbxItemCode1ActionPerformed

    private void btnSuppliedItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppliedItemsActionPerformed
        SuppliedItemsFrame it = new SuppliedItemsFrame();
        it.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnSuppliedItemsActionPerformed

    private void txtDeleteQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeleteQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeleteQuantityActionPerformed

    private void txtAddSellingPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddSellingPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddSellingPriceActionPerformed

    private void txtAddQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddQuantityActionPerformed

    private void txtAddItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddItemNameActionPerformed

    private void txtAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddCategoryActionPerformed

    private void btnLoadAddedItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadAddedItemsActionPerformed
        loadItemsTable();
    }//GEN-LAST:event_btnLoadAddedItemsActionPerformed

    private void btnConfirmAddItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmAddItemsActionPerformed

        // Capture the supplier details
        String itemCode = txtAddItemCode.getText().trim();
        String itemName = txtAddItemName.getText().trim();
        String category = txtAddCategory.getText().trim();
        String quantityStr = txtAddQuantity.getText().trim();
        String sellingPriceStr = txtAddSellingPrice.getText().trim();

        if(itemCode.isEmpty() || itemName.isEmpty() || category.isEmpty()){
            JOptionPane.showMessageDialog(this,"Code, Name and Category cannot be blank.","Input Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!itemCode.matches("I\\d{3}")) {
            JOptionPane.showMessageDialog(this, "Item code must start with 'I' followed by 3 digits.","Input Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        boolean codeExists = itemList.stream().anyMatch(item -> item.getItemCode().equalsIgnoreCase(itemCode));
        if(codeExists){
            JOptionPane.showMessageDialog(this, "Item code already exists.","Input Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        boolean nameExists = itemList.stream().anyMatch(item -> item.getItemName().equalsIgnoreCase(itemName));
        if(nameExists){
            JOptionPane.showMessageDialog(this, "Item name already exists.","Input Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        int quantity;
        double sellingPrice;
        try{
            quantity = Integer.parseInt(quantityStr);
            if (quantity < 0) { // Check for negative quantity
                JOptionPane.showMessageDialog(this, "Quantity cannot be negative.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Quantity must be an integer","Input Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            sellingPrice = Double.parseDouble(sellingPriceStr);
            if (sellingPrice < 0) { // Check for negative cost or selling price
                JOptionPane.showMessageDialog(this, "Selling Price cannot be negative.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Selling Price must be valid numbers.","Input Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Get the selected item codes
        ArrayList<String> selectedSupplierCodes = new ArrayList<>(lstSuppliers.getSelectedValuesList());  // Convert to ArrayList

        // Create the new supplier
        Item newItem = new Item(itemCode, itemName,category, quantity,sellingPrice,selectedSupplierCodes);

        itemList.clear();
        itemManager.read(itemList, Item.class);
        // Add the supplier and associate the items
        boolean success = Item.addItem(itemList,supplierList,  newItem);

        // Update the JTable to show the new supplier
        if (success) {
            // Add to the JTable
            loadItemsTable();
            JOptionPane.showMessageDialog(this, "Item added successfully!");
        }
    }//GEN-LAST:event_btnConfirmAddItemsActionPerformed

    private void txtAddItemCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddItemCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddItemCodeActionPerformed

    private void btnUpdateStocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStocksActionPerformed
        UpdateStockFrame it = new UpdateStockFrame();
        it.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnUpdateStocksActionPerformed

    private void loadItemsTable(){
        itemList.clear();
        // Load items from the file into the ArrayList
        itemManager.read(itemList, Item.class);
        // Add items to the JTable
        DefaultTableModel model = (DefaultTableModel) tblItemsTable.getModel();
        model.setRowCount(0);  // Clear existing rows

        for (Item item : itemList) {
            ArrayList<String> supplierCodes = item.getSupplierCodes();
            String supplierCodesString = (supplierCodes != null && !supplierCodes.isEmpty()) ? String.join(";", supplierCodes) : "NONE";
            System.out.println(supplierCodesString);
            model.addRow(new Object[]{
                item.getItemCode(), 
                item.getItemName(), 
                item.getDescription(), 
                item.getQuantity(), 
                item.getSellingPrice(), 
                supplierCodesString,
                    
            });
        }

        // Optionally, handle case when no items are found
        if (itemList.isEmpty()) {
            lblNoMatchMsg.setVisible(true); // Show no items found message
        } else {
            lblNoMatchMsg.setVisible(false); // Hide the message
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItems;
    private javax.swing.JButton btnConfirmAddItems;
    private javax.swing.JButton btnConfirmDeleteItems;
    private javax.swing.JButton btnConfirmModifyItems;
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JButton btnFilterItems;
    private javax.swing.JButton btnItems;
    private javax.swing.JToggleButton btnLoadAddedItems;
    private javax.swing.JToggleButton btnLoadAllItems;
    private javax.swing.JToggleButton btnLoadModifiedItems;
    private javax.swing.JToggleButton btnLoadUpdatedItems;
    private javax.swing.JButton btnModifyItems;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JButton btnSuppliedItems;
    private javax.swing.JButton btnSuppliers;
    private javax.swing.JButton btnUpdateStocks;
    private javax.swing.JComboBox<String> cbxCategory;
    private javax.swing.JComboBox<String> cbxComparisonOperator;
    private javax.swing.JComboBox<String> cbxItemCode;
    private javax.swing.JComboBox<String> cbxItemCode1;
    private javax.swing.JComboBox<String> cbxItemName;
    private javax.swing.JCheckBox chkViewAllSellingPrice;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelAddItems;
    private javax.swing.JPanel jPanelDeleteItems;
    private javax.swing.JPanel jPanelFilterItems;
    private javax.swing.JPanel jPanelModifyItems;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblCategory1;
    private javax.swing.JLabel lblCategory2;
    private javax.swing.JLabel lblCategory3;
    private javax.swing.JLabel lblCostPrice2;
    private javax.swing.JLabel lblCostPrice4;
    private javax.swing.JLabel lblCostPrice6;
    private javax.swing.JLabel lblItemCode;
    private javax.swing.JLabel lblItemCode1;
    private javax.swing.JLabel lblItemCode2;
    private javax.swing.JLabel lblItemCode3;
    private javax.swing.JLabel lblItemName;
    private javax.swing.JLabel lblItemName1;
    private javax.swing.JLabel lblItemName2;
    private javax.swing.JLabel lblItemName3;
    private javax.swing.JLabel lblNoMatchMsg;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblQuantity1;
    private javax.swing.JLabel lblQuantity2;
    private javax.swing.JLabel lblQuantity3;
    private javax.swing.JLabel lblSellingPrice;
    private javax.swing.JLabel lblSupplierID;
    private javax.swing.JLabel lblSupplierID1;
    private javax.swing.JLabel lblSupplierID2;
    private javax.swing.JLabel lblSupplierID3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JList<String> lstSuppliers;
    private javax.swing.JTable tblItemsTable;
    private javax.swing.JTextField txtAddCategory;
    private javax.swing.JTextField txtAddItemCode;
    private javax.swing.JTextField txtAddItemName;
    private javax.swing.JTextField txtAddQuantity;
    private javax.swing.JTextField txtAddSellingPrice;
    private javax.swing.JTextField txtDeleteCategory;
    private javax.swing.JTextField txtDeleteItemName;
    private javax.swing.JTextField txtDeleteQuantity;
    private javax.swing.JTextField txtDeleteSellingPrice;
    private javax.swing.JTextField txtDeleteSupplier;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtMaxSellingPrice;
    private javax.swing.JTextField txtMinSellingPrice;
    private javax.swing.JTextField txtModifyCategory;
    private javax.swing.JTextField txtModifyItemName;
    private javax.swing.JTextField txtModifyQuantity;
    private javax.swing.JTextField txtModifySellingPrice;
    private javax.swing.JTextField txtModifySupplier;
    private javax.swing.JTextField txtQuantityValue;
    private javax.swing.JTextField txtSupplierID;
    // End of variables declaration//GEN-END:variables
}
