/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventory.manager;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultListModel;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

public class SupplierFrame extends javax.swing.JFrame {

    private ArrayList<Item> itemList = new ArrayList<>();
    private ArrayList<Supplier> supplierList = new ArrayList<>();
    private static FileManager<Item> itemManager = new FileManager<>("./Inventory.txt");
    private static FileManager<Supplier> supplierManager = new FileManager<>("./Supplier.txt");

    
    public SupplierFrame() {
        initComponents();
        setSize(1100, 700);
        lblNoMatchMsg.setVisible(false);
        loadSupplierTable();
        ComboBoxDataLoader readFile = new ComboBoxDataLoader();
        
        // Call the fillComboBox method to populate cbxItemName
        readFile.fillSupplierNameComboBox(cbxSupplierName); 
        readFile.fillHeadquartersComboBox(cbxHeadquaters);

        jPanelAddSupplier.setVisible(false);
        jPanelModifySupplier.setVisible(false);
        jPanelFilterSupplier.setVisible(true);
        jPanelDeleteSupplier.setVisible(false);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jFrame1 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        btnSignOut = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnItems = new javax.swing.JButton();
        btnSuppliers = new javax.swing.JButton();
        btnDeleteSupplier = new javax.swing.JButton();
        btnAddSupplier = new javax.swing.JButton();
        btnModifySupplier = new javax.swing.JButton();
        btnSuppliedItems = new javax.swing.JButton();
        btnUpdateStock = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblNoMatchMsg = new javax.swing.JLabel();
        jPanelFilterSupplier = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblSupplierCode = new javax.swing.JLabel();
        lbllSupplierName = new javax.swing.JLabel();
        lblSupplierID = new javax.swing.JLabel();
        lblHeadquaters = new javax.swing.JLabel();
        txtSupplierCode = new javax.swing.JTextField();
        txtItemID = new javax.swing.JTextField();
        cbxSupplierName = new javax.swing.JComboBox<>();
        cbxHeadquaters = new javax.swing.JComboBox<>();
        btnLoadAllSuppliers = new javax.swing.JToggleButton();
        btnFilterSuppliers = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSupplierTable = new javax.swing.JTable();
        jPanelAddSupplier = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblSupplierCode1 = new javax.swing.JLabel();
        lbllSupplierName1 = new javax.swing.JLabel();
        lblSupplierID1 = new javax.swing.JLabel();
        lblHeadquaters1 = new javax.swing.JLabel();
        txtAddSupplierCode = new javax.swing.JTextField();
        btnConfirmAddSupplier = new javax.swing.JButton();
        txtAddHeadquarters = new javax.swing.JTextField();
        txtAddSupplierName = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstItems = new javax.swing.JList<>();
        lstItems.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        btnLoadAddedSuppliers = new javax.swing.JToggleButton();
        jPanelModifySupplier = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblSupplierCode2 = new javax.swing.JLabel();
        lbllSupplierName2 = new javax.swing.JLabel();
        lblSupplierID2 = new javax.swing.JLabel();
        lblHeadquaters2 = new javax.swing.JLabel();
        btnConfirmModifySupplier = new javax.swing.JButton();
        txtHeadquarters = new javax.swing.JTextField();
        txtSupplierName = new javax.swing.JTextField();
        txtSuppliedItemCodes = new javax.swing.JTextField();
        btnLoadModifiedSuppliers = new javax.swing.JToggleButton();
        cbxSupplierCode = new javax.swing.JComboBox<>();
        jPanelDeleteSupplier = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblSupplierCode3 = new javax.swing.JLabel();
        lbllSupplierName3 = new javax.swing.JLabel();
        lblSupplierID3 = new javax.swing.JLabel();
        lblHeadquaters3 = new javax.swing.JLabel();
        btnConfirmDeleteSupplier = new javax.swing.JButton();
        txtDeleteHeadquarters = new javax.swing.JTextField();
        txtDeleteSupplierName = new javax.swing.JTextField();
        txtDeleteSuppliedItemCodes = new javax.swing.JTextField();
        btnLoadUpdatedSuppliers = new javax.swing.JToggleButton();
        cbxDeleteSupplierCode = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(990, 535));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setPreferredSize(new java.awt.Dimension(4, 40));

        lblUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUser.setText("User: Cheah Thong Yau (Inventory Manager)");

        btnSignOut.setText("Sign Out");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(btnSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnItems.setText("Items");
        btnItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemsActionPerformed(evt);
            }
        });

        btnSuppliers.setText("Suppliers");
        btnSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppliersActionPerformed(evt);
            }
        });

        btnDeleteSupplier.setText("Delete Supplier");
        btnDeleteSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSupplierActionPerformed(evt);
            }
        });

        btnAddSupplier.setText("Add Supplier");
        btnAddSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSupplierActionPerformed(evt);
            }
        });

        btnModifySupplier.setText("Modify Supplier");
        btnModifySupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifySupplierActionPerformed(evt);
            }
        });

        btnSuppliedItems.setText("Supplied Items");
        btnSuppliedItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppliedItemsActionPerformed(evt);
            }
        });

        btnUpdateStock.setText("Update Stock");
        btnUpdateStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnItems, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSuppliedItems, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdateStock, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnModifySupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnItems, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddSupplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteSupplier)
                .addGap(12, 12, 12)
                .addComponent(btnModifySupplier)
                .addGap(18, 18, 18)
                .addComponent(btnSuppliedItems, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateStock, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setPreferredSize(new java.awt.Dimension(119, 50));

        lblTitle.setFont(new java.awt.Font("Bodoni MT Poster Compressed", 1, 24)); // NOI18N
        lblTitle.setText("Supplier");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addContainerGap())
        );

        lblNoMatchMsg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNoMatchMsg.setForeground(new java.awt.Color(255, 0, 0));
        lblNoMatchMsg.setText("No Matching Message");

        jPanelFilterSupplier.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Enter Supplier Details");

        lblSupplierCode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSupplierCode.setText("Supplier Code:");

        lbllSupplierName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbllSupplierName.setText("Supplier Name:");

        lblSupplierID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSupplierID.setText("Item ID:");

        lblHeadquaters.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHeadquaters.setText("Headquaters: ");

        txtSupplierCode.setPreferredSize(new java.awt.Dimension(64, 25));
        txtSupplierCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierCodeActionPerformed(evt);
            }
        });

        txtItemID.setMinimumSize(new java.awt.Dimension(64, 25));
        txtItemID.setPreferredSize(new java.awt.Dimension(64, 25));
        txtItemID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemIDActionPerformed(evt);
            }
        });

        cbxSupplierName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Supplier 1", "Supplier 2", "Supplier 3", "Supplier 4" }));
        cbxSupplierName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSupplierNameActionPerformed(evt);
            }
        });

        cbxHeadquaters.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Location 1", "Location 2", "Location 3", "Location 4" }));
        cbxHeadquaters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxHeadquatersActionPerformed(evt);
            }
        });

        btnLoadAllSuppliers.setText("Load All Data");
        btnLoadAllSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadAllSuppliersActionPerformed(evt);
            }
        });

        btnFilterSuppliers.setText("Filter");
        btnFilterSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterSuppliersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFilterSupplierLayout = new javax.swing.GroupLayout(jPanelFilterSupplier);
        jPanelFilterSupplier.setLayout(jPanelFilterSupplierLayout);
        jPanelFilterSupplierLayout.setHorizontalGroup(
            jPanelFilterSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFilterSupplierLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelFilterSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFilterSupplierLayout.createSequentialGroup()
                        .addGroup(jPanelFilterSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelFilterSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelFilterSupplierLayout.createSequentialGroup()
                                    .addGroup(jPanelFilterSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelFilterSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbllSupplierName)
                                            .addComponent(lblHeadquaters, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(lblSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(32, 32, 32)
                                    .addGroup(jPanelFilterSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtItemID, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbxSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbxHeadquaters, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanelFilterSupplierLayout.createSequentialGroup()
                                    .addGap(85, 85, 85)
                                    .addComponent(btnFilterSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelFilterSupplierLayout.createSequentialGroup()
                                .addComponent(lblSupplierCode)
                                .addGap(34, 34, 34)
                                .addComponent(txtSupplierCode, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFilterSupplierLayout.createSequentialGroup()
                        .addComponent(btnLoadAllSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))))
            .addGroup(jPanelFilterSupplierLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelFilterSupplierLayout.setVerticalGroup(
            jPanelFilterSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilterSupplierLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addGroup(jPanelFilterSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSupplierCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSupplierCode))
                .addGap(18, 18, 18)
                .addGroup(jPanelFilterSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllSupplierName)
                    .addComponent(cbxSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelFilterSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeadquaters)
                    .addComponent(cbxHeadquaters, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelFilterSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFilterSupplierLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblSupplierID))
                    .addGroup(jPanelFilterSupplierLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(txtItemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(btnFilterSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLoadAllSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblSupplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Supplier Code", "Name", "Location", "Supplied Item Codes"
            }
        ));
        jScrollPane2.setViewportView(tblSupplierTable);

        jScrollPane5.setViewportView(jScrollPane2);

        jScrollPane3.setViewportView(jScrollPane5);

        jPanelAddSupplier.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Add Supplier");

        lblSupplierCode1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSupplierCode1.setText("Supplier Code:");

        lbllSupplierName1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbllSupplierName1.setText("Supplier Name:");

        lblSupplierID1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSupplierID1.setText("Item ID:");

        lblHeadquaters1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHeadquaters1.setText("Headquaters: ");

        txtAddSupplierCode.setPreferredSize(new java.awt.Dimension(64, 25));
        txtAddSupplierCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddSupplierCodeActionPerformed(evt);
            }
        });

        btnConfirmAddSupplier.setText("Add Supplier");
        btnConfirmAddSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmAddSupplierActionPerformed(evt);
            }
        });

        txtAddHeadquarters.setPreferredSize(new java.awt.Dimension(64, 25));
        txtAddHeadquarters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddHeadquartersActionPerformed(evt);
            }
        });

        txtAddSupplierName.setPreferredSize(new java.awt.Dimension(64, 25));
        txtAddSupplierName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddSupplierNameActionPerformed(evt);
            }
        });

        lstItems.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "I001", "I002", "I003", "I004", "I005" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstItemsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstItems);

        jScrollPane4.setViewportView(jScrollPane1);

        btnLoadAddedSuppliers.setText("Load All Data");
        btnLoadAddedSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadAddedSuppliersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAddSupplierLayout = new javax.swing.GroupLayout(jPanelAddSupplier);
        jPanelAddSupplier.setLayout(jPanelAddSupplierLayout);
        jPanelAddSupplierLayout.setHorizontalGroup(
            jPanelAddSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddSupplierLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelAddSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddSupplierLayout.createSequentialGroup()
                                .addComponent(lblSupplierID1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53))
                            .addGroup(jPanelAddSupplierLayout.createSequentialGroup()
                                .addComponent(lbllSupplierName1)
                                .addGap(34, 34, 34)))
                        .addGroup(jPanelAddSupplierLayout.createSequentialGroup()
                            .addComponent(lblHeadquaters1)
                            .addGap(42, 42, 42)))
                    .addGroup(jPanelAddSupplierLayout.createSequentialGroup()
                        .addComponent(lblSupplierCode1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanelAddSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddHeadquarters, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddSupplierCode, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelAddSupplierLayout.createSequentialGroup()
                .addGroup(jPanelAddSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAddSupplierLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanelAddSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLoadAddedSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConfirmAddSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelAddSupplierLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAddSupplierLayout.setVerticalGroup(
            jPanelAddSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddSupplierLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addGroup(jPanelAddSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplierCode1)
                    .addComponent(txtAddSupplierCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanelAddSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllSupplierName1)
                    .addComponent(txtAddSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAddSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeadquaters1)
                    .addComponent(txtAddHeadquarters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanelAddSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSupplierID1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnConfirmAddSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLoadAddedSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelModifySupplier.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Modify Supplier");

        lblSupplierCode2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSupplierCode2.setText("Supplier Code:");

        lbllSupplierName2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbllSupplierName2.setText("Supplier Name:");

        lblSupplierID2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSupplierID2.setText("Item ID:");

        lblHeadquaters2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHeadquaters2.setText("Headquaters: ");

        btnConfirmModifySupplier.setText("Modify Supplier");
        btnConfirmModifySupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmModifySupplierActionPerformed(evt);
            }
        });

        txtHeadquarters.setPreferredSize(new java.awt.Dimension(64, 25));
        txtHeadquarters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeadquartersActionPerformed(evt);
            }
        });

        txtSupplierName.setPreferredSize(new java.awt.Dimension(64, 25));
        txtSupplierName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierNameActionPerformed(evt);
            }
        });

        txtSuppliedItemCodes.setMinimumSize(new java.awt.Dimension(64, 25));
        txtSuppliedItemCodes.setPreferredSize(new java.awt.Dimension(64, 25));
        txtSuppliedItemCodes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuppliedItemCodesActionPerformed(evt);
            }
        });

        btnLoadModifiedSuppliers.setText("Load All Data");
        btnLoadModifiedSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadModifiedSuppliersActionPerformed(evt);
            }
        });

        cbxSupplierCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Supplier 1", "Supplier 2", "Supplier 3", "Supplier 4" }));
        cbxSupplierCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSupplierCodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelModifySupplierLayout = new javax.swing.GroupLayout(jPanelModifySupplier);
        jPanelModifySupplier.setLayout(jPanelModifySupplierLayout);
        jPanelModifySupplierLayout.setHorizontalGroup(
            jPanelModifySupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModifySupplierLayout.createSequentialGroup()
                .addGroup(jPanelModifySupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModifySupplierLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanelModifySupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelModifySupplierLayout.createSequentialGroup()
                                .addComponent(lblSupplierCode2)
                                .addGap(39, 39, 39)
                                .addComponent(cbxSupplierCode, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelModifySupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelModifySupplierLayout.createSequentialGroup()
                                    .addGap(50, 50, 50)
                                    .addGroup(jPanelModifySupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnConfirmModifySupplier, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                        .addComponent(btnLoadModifiedSuppliers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanelModifySupplierLayout.createSequentialGroup()
                                    .addGroup(jPanelModifySupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModifySupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModifySupplierLayout.createSequentialGroup()
                                                .addComponent(lblSupplierID2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(53, 53, 53))
                                            .addGroup(jPanelModifySupplierLayout.createSequentialGroup()
                                                .addComponent(lbllSupplierName2)
                                                .addGap(34, 34, 34)))
                                        .addGroup(jPanelModifySupplierLayout.createSequentialGroup()
                                            .addComponent(lblHeadquaters2)
                                            .addGap(42, 42, 42)))
                                    .addGroup(jPanelModifySupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtHeadquarters, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSuppliedItemCodes, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanelModifySupplierLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel5)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanelModifySupplierLayout.setVerticalGroup(
            jPanelModifySupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModifySupplierLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addGap(45, 45, 45)
                .addGroup(jPanelModifySupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSupplierCode2)
                    .addComponent(cbxSupplierCode, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelModifySupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllSupplierName2)
                    .addComponent(txtSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelModifySupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeadquaters2)
                    .addComponent(txtHeadquarters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanelModifySupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSupplierID2)
                    .addComponent(txtSuppliedItemCodes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(btnConfirmModifySupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLoadModifiedSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDeleteSupplier.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Delete Supplier");

        lblSupplierCode3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSupplierCode3.setText("Supplier Code:");

        lbllSupplierName3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbllSupplierName3.setText("Supplier Name:");

        lblSupplierID3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSupplierID3.setText("Item ID:");

        lblHeadquaters3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHeadquaters3.setText("Headquaters: ");

        btnConfirmDeleteSupplier.setText("Delete Supplier");
        btnConfirmDeleteSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmDeleteSupplierActionPerformed(evt);
            }
        });

        txtDeleteHeadquarters.setPreferredSize(new java.awt.Dimension(64, 25));
        txtDeleteHeadquarters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeleteHeadquartersActionPerformed(evt);
            }
        });

        txtDeleteSupplierName.setPreferredSize(new java.awt.Dimension(64, 25));
        txtDeleteSupplierName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeleteSupplierNameActionPerformed(evt);
            }
        });

        txtDeleteSuppliedItemCodes.setMinimumSize(new java.awt.Dimension(64, 25));
        txtDeleteSuppliedItemCodes.setPreferredSize(new java.awt.Dimension(64, 25));
        txtDeleteSuppliedItemCodes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeleteSuppliedItemCodesActionPerformed(evt);
            }
        });

        btnLoadUpdatedSuppliers.setText("Load All Data");
        btnLoadUpdatedSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadUpdatedSuppliersActionPerformed(evt);
            }
        });

        cbxDeleteSupplierCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Supplier 1", "Supplier 2", "Supplier 3", "Supplier 4" }));
        cbxDeleteSupplierCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDeleteSupplierCodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDeleteSupplierLayout = new javax.swing.GroupLayout(jPanelDeleteSupplier);
        jPanelDeleteSupplier.setLayout(jPanelDeleteSupplierLayout);
        jPanelDeleteSupplierLayout.setHorizontalGroup(
            jPanelDeleteSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeleteSupplierLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelDeleteSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelDeleteSupplierLayout.createSequentialGroup()
                        .addComponent(lblSupplierCode3)
                        .addGap(39, 39, 39)
                        .addComponent(cbxDeleteSupplierCode, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDeleteSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelDeleteSupplierLayout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addGroup(jPanelDeleteSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnConfirmDeleteSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                .addComponent(btnLoadUpdatedSuppliers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanelDeleteSupplierLayout.createSequentialGroup()
                            .addGroup(jPanelDeleteSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDeleteSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDeleteSupplierLayout.createSequentialGroup()
                                        .addComponent(lblSupplierID3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53))
                                    .addGroup(jPanelDeleteSupplierLayout.createSequentialGroup()
                                        .addComponent(lbllSupplierName3)
                                        .addGap(34, 34, 34)))
                                .addGroup(jPanelDeleteSupplierLayout.createSequentialGroup()
                                    .addComponent(lblHeadquaters3)
                                    .addGap(42, 42, 42)))
                            .addGroup(jPanelDeleteSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDeleteHeadquarters, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDeleteSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDeleteSuppliedItemCodes, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDeleteSupplierLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(85, 85, 85))
        );
        jPanelDeleteSupplierLayout.setVerticalGroup(
            jPanelDeleteSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeleteSupplierLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addGap(40, 40, 40)
                .addGroup(jPanelDeleteSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSupplierCode3)
                    .addComponent(cbxDeleteSupplierCode, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDeleteSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllSupplierName3)
                    .addComponent(txtDeleteSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDeleteSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeadquaters3)
                    .addComponent(txtDeleteHeadquarters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanelDeleteSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSupplierID3)
                    .addComponent(txtDeleteSuppliedItemCodes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(btnConfirmDeleteSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLoadUpdatedSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1830, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNoMatchMsg)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelFilterSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanelAddSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanelModifySupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelDeleteSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 2003, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(lblNoMatchMsg)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelFilterSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAddSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelModifySupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDeleteSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstItemsMouseClicked

    }//GEN-LAST:event_lstItemsMouseClicked

    private void txtAddSupplierNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddSupplierNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddSupplierNameActionPerformed

    private void txtAddHeadquartersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddHeadquartersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddHeadquartersActionPerformed

    private void btnConfirmAddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmAddSupplierActionPerformed

        // Capture the supplier details
        String supplierCode = txtAddSupplierCode.getText().trim();
        String supplierName = txtAddSupplierName.getText().trim();
        String headquarters = txtAddHeadquarters.getText().trim();

        if(supplierCode.isEmpty() || supplierName.isEmpty() || headquarters.isEmpty()){
            JOptionPane.showMessageDialog(this,"Code, Name and Location cannot be blank","Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!supplierCode.matches("S\\d{3}")) {
            JOptionPane.showMessageDialog(this, "Supplier code must start with 'S' followed by 3 digits.","Input Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        boolean codeExists = supplierList.stream().anyMatch(supplier -> supplier.getSupplierCode().equalsIgnoreCase(supplierCode));
        if(codeExists){
            JOptionPane.showMessageDialog(this, "Supplier code already exists.","Input Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        boolean nameExists = supplierList.stream().anyMatch(supplier -> supplier.getSupplierName().equalsIgnoreCase(supplierName));
        if(nameExists){
            JOptionPane.showMessageDialog(this, "Supplier name already exists.","Input Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Get the selected item codes
        ArrayList<String> selectedItemCodes = new ArrayList<>(lstItems.getSelectedValuesList());  // Convert to ArrayList

        // Create the new supplier
        Supplier newSupplier = new Supplier(supplierCode, supplierName, headquarters, selectedItemCodes);
        
        supplierList.clear();
        supplierManager.read(supplierList, Supplier.class);

        // Add the supplier and associate the items
        boolean success = Supplier.addSupplier(supplierList, itemList, newSupplier);

        // Update the JTable to show the new supplier
        if (success) {
            // Add to the JTable
            loadSupplierTable();

            JOptionPane.showMessageDialog(this, "Supplier added successfully!");
        } else {
            JOptionPane.showMessageDialog(this, "Supplier with this code or name already exists.");
        }
    }//GEN-LAST:event_btnConfirmAddSupplierActionPerformed

    private void txtAddSupplierCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddSupplierCodeActionPerformed

    }//GEN-LAST:event_txtAddSupplierCodeActionPerformed

    private void btnFilterSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterSuppliersActionPerformed

        String supplierCodeInput = txtSupplierCode.getText();
        String supplierNameInput = (String) cbxSupplierName.getSelectedItem();
        String headquartersInput = (String) cbxHeadquaters.getSelectedItem();
        String itemIDInput = txtItemID.getText();

        List<String> matchingRows = Supplier.filterSuppliersTable(supplierCodeInput, supplierNameInput, headquartersInput, itemIDInput);

        DefaultTableModel tableModel = (DefaultTableModel) tblSupplierTable.getModel();

        tableModel.setRowCount(0);

        if (!matchingRows.isEmpty()) {
            for (String row : matchingRows) {
                String[] parts = row.split(",");
                String supplierCode = parts[0].trim();
                String supplierName = parts[1].trim();
                String headquarters = parts[2].trim();
                String itemCodesString = String.join(";", Arrays.asList(parts).subList(3, parts.length));

                tableModel.addRow(new Object[]{supplierCode, supplierName, headquarters, itemCodesString});
            }
            lblNoMatchMsg.setVisible(false);
        } else {
            lblNoMatchMsg.setVisible(true);
            lblNoMatchMsg.setText("No Matching Items");
        }
    }//GEN-LAST:event_btnFilterSuppliersActionPerformed

    private void btnLoadAllSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadAllSuppliersActionPerformed
        loadSupplierTable();
    }//GEN-LAST:event_btnLoadAllSuppliersActionPerformed

    private void cbxHeadquatersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxHeadquatersActionPerformed

    }//GEN-LAST:event_cbxHeadquatersActionPerformed

    private void cbxSupplierNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSupplierNameActionPerformed

    }//GEN-LAST:event_cbxSupplierNameActionPerformed

    private void txtItemIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemIDActionPerformed

    private void txtSupplierCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierCodeActionPerformed

    private void btnAddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSupplierActionPerformed
        jPanelAddSupplier.setVisible(true);
        jPanelModifySupplier.setVisible(false);
        jPanelFilterSupplier.setVisible(false);
        jPanelDeleteSupplier.setVisible(false);

        itemManager.read(itemList, Item.class);
        // Example: Assuming lstItems is a JList and itemsList is an ArrayList of items
        DefaultListModel<String> listModel = new DefaultListModel<>();
        for (Item item : itemList) {
            listModel.addElement(item.getItemCode());  // or item.getItemName() based on your requirement
        }
        lstItems.setModel(listModel);  // Set the model to the JList
    }//GEN-LAST:event_btnAddSupplierActionPerformed

    private void btnSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppliersActionPerformed
        jPanelAddSupplier.setVisible(false);
        jPanelModifySupplier.setVisible(false);
        jPanelFilterSupplier.setVisible(true);
        jPanelDeleteSupplier.setVisible(false);
    }//GEN-LAST:event_btnSuppliersActionPerformed

    private void btnItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemsActionPerformed
        ItemsFrame it = new ItemsFrame();
        it.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnItemsActionPerformed

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void btnConfirmModifySupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmModifySupplierActionPerformed
        String supplierCode = (String) cbxSupplierCode.getSelectedItem();
        String supplierName = txtSupplierName.getText().trim();
        String headquarters = txtHeadquarters.getText().trim();
        String suppliedItemCodesStr = txtSuppliedItemCodes.getText().trim();
        
        supplierList.clear();
        supplierManager.read(supplierList, Supplier.class);
        itemList.clear();
        itemManager.read(itemList, Item.class);
        // Validation checks
        if (supplierName.isEmpty() || headquarters.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Supplier Name and Headquarters cannot be blank.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean nameExists = supplierList.stream().anyMatch(supplier -> supplier.getSupplierName().equalsIgnoreCase(supplierName) &&!supplier.getSupplierCode().equals(supplierCode));
        if(nameExists){
            JOptionPane.showMessageDialog(this, "Supplier name already exists.","Input Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
       
        ArrayList<String> itemCodes = new ArrayList<>(Arrays.asList(suppliedItemCodesStr.split(";")));

        boolean success = Supplier.modifySupplier(supplierList, itemList, supplierCode,supplierName,headquarters,itemCodes);
        
        if (success) {
             loadSupplierTable();
             JOptionPane.showMessageDialog(this, "Supplier modified successfully!");
         } else {
             JOptionPane.showMessageDialog(this, "One or more item codes are invalid.");
        }
    }//GEN-LAST:event_btnConfirmModifySupplierActionPerformed

    private void txtHeadquartersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeadquartersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeadquartersActionPerformed

    private void txtSupplierNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierNameActionPerformed

    private void cbxSupplierCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSupplierCodeActionPerformed
        String selectedSupplierCode = (String) cbxSupplierCode.getSelectedItem();

        Supplier selectedSupplier = Supplier.findSupplierByCode(supplierList, selectedSupplierCode);
        if (selectedSupplier != null) {
            // Autofill the text fields with the supplier data
            txtSupplierName.setText(selectedSupplier.getSupplierName());
            txtHeadquarters.setText(selectedSupplier.getHqLocation());
            
            ArrayList<String> suppliedItemCodes = selectedSupplier.getSuppliedItemCodes();
            txtSuppliedItemCodes.setText(suppliedItemCodes!= null? String.join(";", suppliedItemCodes):"");
        }      
    }//GEN-LAST:event_cbxSupplierCodeActionPerformed

    private void txtSuppliedItemCodesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuppliedItemCodesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuppliedItemCodesActionPerformed

    private void btnModifySupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifySupplierActionPerformed
        ComboBoxDataLoader readFile = new ComboBoxDataLoader();

        readFile.fillSupplierCodeComboBox(cbxSupplierCode);
        
        jPanelAddSupplier.setVisible(false);
        jPanelModifySupplier.setVisible(true);
        jPanelFilterSupplier.setVisible(false);
        jPanelDeleteSupplier.setVisible(false);
    }//GEN-LAST:event_btnModifySupplierActionPerformed

    private void btnLoadModifiedSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadModifiedSuppliersActionPerformed
        loadSupplierTable();
    }//GEN-LAST:event_btnLoadModifiedSuppliersActionPerformed

    private void btnLoadAddedSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadAddedSuppliersActionPerformed
        loadSupplierTable();
    }//GEN-LAST:event_btnLoadAddedSuppliersActionPerformed

    private void btnConfirmDeleteSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmDeleteSupplierActionPerformed
        String supplierCode = (String) cbxDeleteSupplierCode.getSelectedItem();
        
        supplierList.clear();
        supplierManager.read(supplierList, Supplier.class);
        itemList.clear();
        itemManager.read(itemList, Item.class);
        // Validation checks
        if(supplierCode.equals("NONE")){
            JOptionPane.showMessageDialog(this, "Select a supplier to delete.");
            return;     
        }    
        
        supplierList.clear();
        supplierManager.read(supplierList, Supplier.class);
        Supplier.deleteSupplier(supplierList,itemList,supplierCode);
        
        loadSupplierTable();
        JOptionPane.showMessageDialog(this, "Supplier deleted successfully!");
    }//GEN-LAST:event_btnConfirmDeleteSupplierActionPerformed

    private void txtDeleteHeadquartersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeleteHeadquartersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeleteHeadquartersActionPerformed

    private void txtDeleteSupplierNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeleteSupplierNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeleteSupplierNameActionPerformed

    private void txtDeleteSuppliedItemCodesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeleteSuppliedItemCodesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeleteSuppliedItemCodesActionPerformed

    private void btnLoadUpdatedSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadUpdatedSuppliersActionPerformed
        loadSupplierTable();
    }//GEN-LAST:event_btnLoadUpdatedSuppliersActionPerformed

    private void cbxDeleteSupplierCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDeleteSupplierCodeActionPerformed
        String selectedSupplierCode = (String) cbxDeleteSupplierCode.getSelectedItem();

        Supplier selectedSupplier = Supplier.findSupplierByCode(supplierList, selectedSupplierCode);
        if (selectedSupplier != null) {
            // Autofill the text fields with the supplier data
            txtDeleteSupplierName.setText(selectedSupplier.getSupplierName());
            txtDeleteHeadquarters.setText(selectedSupplier.getHqLocation());
            
            ArrayList<String> suppliedItemCodes = selectedSupplier.getSuppliedItemCodes();
            txtDeleteSuppliedItemCodes.setText(suppliedItemCodes!= null? String.join(";", suppliedItemCodes):"");
        }
        txtDeleteSupplierName.setEnabled(false);
        txtDeleteHeadquarters.setEnabled(false);
        txtDeleteSuppliedItemCodes.setEnabled(false);
        
    }//GEN-LAST:event_cbxDeleteSupplierCodeActionPerformed

    private void btnDeleteSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSupplierActionPerformed
        ComboBoxDataLoader readFile = new ComboBoxDataLoader();

        readFile.fillSupplierCodeComboBox(cbxDeleteSupplierCode);
        
        jPanelAddSupplier.setVisible(false);
        jPanelModifySupplier.setVisible(false);
        jPanelFilterSupplier.setVisible(false);
        jPanelDeleteSupplier.setVisible(true);
    }//GEN-LAST:event_btnDeleteSupplierActionPerformed

    private void btnSuppliedItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppliedItemsActionPerformed
        SuppliedItemsFrame it = new SuppliedItemsFrame();
        it.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnSuppliedItemsActionPerformed

    private void btnUpdateStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStockActionPerformed
        UpdateStockFrame it = new UpdateStockFrame();
        it.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnUpdateStockActionPerformed

    private void loadSupplierTable() {
        supplierList.clear();
        // Load items from the file into the ArrayList
        supplierManager.read(supplierList, Supplier.class);

        // Get the table model
        DefaultTableModel model = (DefaultTableModel) tblSupplierTable.getModel();
        model.setRowCount(0);  // Clear existing rows
        
        for (Supplier supplier : supplierList) {
            ArrayList<String> suppliedItemCodes = supplier.getSuppliedItemCodes();
            String suppliedItemCodesStr = (suppliedItemCodes != null && !suppliedItemCodes.isEmpty()) ? String.join(";", suppliedItemCodes) : "NONE";
            
            model.addRow(new Object[]{
                supplier.getSupplierCode(),
                supplier.getSupplierName(),
                supplier.getHqLocation(),
                suppliedItemCodesStr,
            });
        }
        

        // Optionally, handle case when no items are found
        if (supplierList.isEmpty()) {
            lblNoMatchMsg.setVisible(true); // Show no items found message
        } else {
            lblNoMatchMsg.setVisible(false); // Hide the message
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplierFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSupplier;
    private javax.swing.JButton btnConfirmAddSupplier;
    private javax.swing.JButton btnConfirmDeleteSupplier;
    private javax.swing.JButton btnConfirmModifySupplier;
    private javax.swing.JButton btnDeleteSupplier;
    private javax.swing.JButton btnFilterSuppliers;
    private javax.swing.JButton btnItems;
    private javax.swing.JToggleButton btnLoadAddedSuppliers;
    private javax.swing.JToggleButton btnLoadAllSuppliers;
    private javax.swing.JToggleButton btnLoadModifiedSuppliers;
    private javax.swing.JToggleButton btnLoadUpdatedSuppliers;
    private javax.swing.JButton btnModifySupplier;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JButton btnSuppliedItems;
    private javax.swing.JButton btnSuppliers;
    private javax.swing.JButton btnUpdateStock;
    private javax.swing.JComboBox<String> cbxDeleteSupplierCode;
    private javax.swing.JComboBox<String> cbxHeadquaters;
    private javax.swing.JComboBox<String> cbxSupplierCode;
    private javax.swing.JComboBox<String> cbxSupplierName;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelAddSupplier;
    private javax.swing.JPanel jPanelDeleteSupplier;
    private javax.swing.JPanel jPanelFilterSupplier;
    private javax.swing.JPanel jPanelModifySupplier;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblHeadquaters;
    private javax.swing.JLabel lblHeadquaters1;
    private javax.swing.JLabel lblHeadquaters2;
    private javax.swing.JLabel lblHeadquaters3;
    private javax.swing.JLabel lblNoMatchMsg;
    private javax.swing.JLabel lblSupplierCode;
    private javax.swing.JLabel lblSupplierCode1;
    private javax.swing.JLabel lblSupplierCode2;
    private javax.swing.JLabel lblSupplierCode3;
    private javax.swing.JLabel lblSupplierID;
    private javax.swing.JLabel lblSupplierID1;
    private javax.swing.JLabel lblSupplierID2;
    private javax.swing.JLabel lblSupplierID3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lbllSupplierName;
    private javax.swing.JLabel lbllSupplierName1;
    private javax.swing.JLabel lbllSupplierName2;
    private javax.swing.JLabel lbllSupplierName3;
    private javax.swing.JList<String> lstItems;
    private javax.swing.JTable tblSupplierTable;
    private javax.swing.JTextField txtAddHeadquarters;
    private javax.swing.JTextField txtAddSupplierCode;
    private javax.swing.JTextField txtAddSupplierName;
    private javax.swing.JTextField txtDeleteHeadquarters;
    private javax.swing.JTextField txtDeleteSuppliedItemCodes;
    private javax.swing.JTextField txtDeleteSupplierName;
    private javax.swing.JTextField txtHeadquarters;
    private javax.swing.JTextField txtItemID;
    private javax.swing.JTextField txtSuppliedItemCodes;
    private javax.swing.JTextField txtSupplierCode;
    private javax.swing.JTextField txtSupplierName;
    // End of variables declaration//GEN-END:variables
}
